### ISSUE TITLE
issue not showing correct data

### ISSUE THREAD

**Issue by killmasta93** [sebastian13/zabbix-template-speedtest#1]
Hi, I was testing it out and on the graph shows 20mb but on the terminal it shows differently 
```


2021-02-17-19:36:15
Running Speedtest
ping: 56.937, down: 20490697.44710618, up: 8613410.034235975, server: Claro Colombia
Sending Data to Zabbix
info from server: "processed: 7; failed: 0; total: 7; seconds spent: 0.000201"
sent: 7; skipped: 0; total: 7
```

![image](https://user-images.githubusercontent.com/13953629/108286920-f4516300-7157-11eb-9725-5d8583b0ae4c.png)

Thank you

**Comment by sebastian13** [comment]
Hi @killmasta93,

the script is sending the values in bits. As 20490697 bit isn't nicely readable, Zabbix is showing you the values as 20,49 Mbps. It's sill the same value. Or do I get anything wrong here?

**Comment by killmasta93** [comment]
thanks for the reply, whats odd is that i run the speed test on windows i get higher value
![image](https://user-images.githubusercontent.com/13953629/108440479-372b3d80-7221-11eb-8dc5-be75a892f4c4.png)

**Comment by killmasta93** [comment]
bump any updates?

**Comment by killmasta93** [comment]
it was an firewall issue as we have dual wan so it was not getting the correct value thank you again
